services:
  postgres:
    image: postgres:16
    container_name: logistics_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=logistics
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: