
spring.application.name=transport-logistics

spring.datasource.url=jdbc:postgresql://localhost:5432/logistics
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=${JWT_SECRET:a4Dgw76tekr02oT1VBASyoq58fcHrlJW8pudwzIGgkw=}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}